export const GET_MOVIE_FROM_API_SUCCESS = "GET_MOVIE_FROM_API_SUCCESS";
export const GET_MOVIE_FROM_API_FAIL = "GET_MOVIE_FROM_API_FAIL";
export const SAVE_MOVIE_TO_DATABASE_SUCCESS = "SAVE_MOVIE_TO_DATABASE_SUCCESS";
export const SAVE_MOVIE_TO_DATABASE_FAIL = "SAVE_MOVIE_TO_DATABASE_FAIL";
export const GET_MOVIES_FROM_DATABASE_SUCCESS = "GET_MOVIES_FROM_DATABASE_SUCCESS";
export const GET_MOVIES_FROM_DATABASE_FAIL = "GET_MOVIES_FROM_DATABASE_FAIL";
export const GET_COMMENTS_FROM_DATABASE_SUCCESS = "GET_COMMENTS_FROM_DATABASE_SUCCESS";
export const GET_COMMENTS_FROM_DATABASE_FAIL = "GET_COMMENTS_FROM_DATABASE_FAIL";

export const CHANGE_MOVIE_DATA = "CHANGE_MOVIE_DATA";